### PR TITLE
Upgrade SBT to 1.0.3.

### PR DESCRIPTION
**Pull request by aa8y**
Upgrades SBT and the corresponding plugins to the latest version.

### CODE REVIEW

**Comment by maqdev** [comment]
I already tried updating to sbt `1.0.0` but got stuck with this: https://github.com/sbt/sbt/issues/3431

Let's see how things will go with `1.0.3`

**Comment by aa8y** [comment]
@maqdev I wasn't sure if this warrants a version change. Do let me know if you need me to make any changes before accepting the PR.

**Comment by aa8y** [comment]
@maqdev What about [this comment](https://github.com/sbt/sbt/issues/3431#issuecomment-336693950) in that issue? It seems like they expected SBT 1.0.3 to fix this. I am not sure how to test it.

**Comment by aa8y** [comment]
Well, maybe not fix it. But help figure out what the problem is? Maybe the current [last comment](https://github.com/sbt/sbt/issues/3431#issuecomment-340069886) is a workaround?

**Comment by maqdev** [comment]
It seems the bug still there... https://travis-ci.org/hypertino/inflector/jobs/295503521
Somehow fails publish with OSS Sonatype plugin

**Comment by maqdev** [comment]
Let's see if that comment helps.

**Comment by maqdev** [comment]
So the problem is only with SNAPSHOTS, I've merged your PR in a command line and released `1.0.7`. Thanks for contribution.

**Comment by maqdev** [comment]
Wow it seems there is one more problem with sbt `1.0.3`: 
`sbt ++2.11.11 publishLocal` ignores version and publishes for `2.12`

**Pull request closed without merging**
